#!/usr/bin/env bash

server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}

	location /airbnb-onepage/ {
		proxy_pass http://localhost:5000;
	}


	error_page 404 /404.html;
	location = /404.html {
		root /var/www/error/;
		internal;
	}
}
